spring.application.name=spring-gift
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.name=sa
spring.datasource.password=
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true